Config = {}
Config.KitItem = 'antilag_kit'
Config.InstallTime = 10000
Config.RemoveTime = 10000
Config.MechanicJobs = { mechanic=true, mechanic2=true }

Config.MinSpeedKmh = 5.0
Config.Range = 220.0

-- V4.4.2 sound source:
--   'synth'  = pops/bangs generated by the resource itself (html/index.html). Always works,
--              no GTA audio banks needed. Volume/muffling by distance. (default)
--   'native' = GTA soundsets below. Depends on game audio banks; can be silent on some setups.
Config.SoundMode = 'synth'
Config.SoundVolume = 0.9   -- 0.0 - 1.5
Config.SoundRange = 120.0  -- metres; beyond this nearby players hear nothing

-- Native GTA audio (only used when Config.SoundMode = 'native'). Optional `bank = '...'`
-- per sound is loaded with RequestScriptAudioBank first. These are emitted FROM the vehicle, so GTA handles 3D positioning.
Config.NativeSounds = {
    pop  = { name = 'BOOT_POP', set = 'DLC_VW_BODY_DISPOSAL_SOUNDS' },
    bang = { name = 'Explosion_01', set = 'FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS' },
    mega = { name = 'Explosion_04', set = 'FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS' },
    big  = { name = 'Explosion_04', set = 'FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS' }
}

-- V4 uses driver input instead of addon-dependent RPM values.
Config.LimiterThrottle = 0.82
Config.LimiterHoldMs = 300
Config.LiftThrottleBefore = 0.55
Config.LiftThrottleAfter = 0.08
Config.LiftCooldownMs = 520

-- Burst patterns: { kind, gap after this shot in ms }. kind = 'pop' | 'bang' | 'mega' | 'big'.
-- Keep gaps >= 75ms so nearby players receive every shot (server rate gate is 70ms).
-- (The held-throttle 2-step is a continuous barrage, see Config.Intensity.)
Config.LiftSequence = {         -- lift off at speed
    { 'bang', 100 }, { 'pop', 90 }, { 'mega', 240 }, { 'big', 0 }
}

-- BIG bangs: a separate, much heavier explosion that lands after the crackle.
Config.BigBang = {
    CrackleFinale = true,    -- end every overrun crackle with a BIG bang
    FinaleDelayMs = 150,     -- pause after the last crackle before the BIG bang
    CrackleChance = 0.04,    -- chance any crackle shot is a BIG bang
    Shake = 0.025,           -- camera shake for players close by (0 = off, 0.1 = heavy)
    ShakeRange = 12.0,       -- metres
}
Config.HugeFlameScale = 3.0  -- flame size for BIG bangs

-- Gear change: pops -> bang -> BIG bang on every shift while driving.
Config.GearChange = {
    Enabled = true,
    Downshifts = false,      -- true = also fire on downshifts
    MinSpeedKmh = 10.0,
    CooldownMs = 700,        -- ignore shifts closer together than this
    Sequence = { { 'pop', 80 }, { 'pop', 85 }, { 'bang', 180 }, { 'big', 0 } },
}

Config.FlameScale = 1.55
Config.BigFlameScale = 2.15

---------------------------------------------------------------------
-- V4.4 POPS & BANGS (overrun crackle)
---------------------------------------------------------------------
-- A "pops & bangs" map: while coasting off-throttle the exhaust keeps crackling
-- with irregular pops and the occasional bang until you get back on it or slow down.
-- Can be switched on/off per vehicle from the /antilag menu.
Config.PopsBangs = {
    Enabled = true,          -- master switch for the whole feature
    DefaultOn = true,        -- state for newly fitted vehicles
    MinSpeedKmh = 25.0,      -- only crackle above this speed
    MaxThrottle = 0.08,      -- counts as "off throttle" at or below this
    StartDelayMs = 800,      -- wait after lift-off before the crackle starts (lets the lift burst + BIG bang play)
    MaxDurationMs = 4500,    -- stop crackling after this long on the overrun
    MinGapMs = 90,           -- shortest gap between pops (server rate gate is 70ms)
    MaxGapMs = 260,          -- longest gap between pops
    BangChance = 0.30,       -- chance any shot is a bang instead of a pop
    MegaChance = 0.15,       -- chance any shot is a mega bang
    FlameChance = 0.55,      -- chance a plain pop also spits a flame (bangs always flame)
}

---------------------------------------------------------------------
-- V4.4 FLAME COLOURS
---------------------------------------------------------------------
-- Who may change a fitted vehicle's settings from the panel:
--   'driver'   = whoever is in the driver seat of a fitted vehicle
--   'mechanic' = only mechanics (Config.MechanicJobs) in the driver seat
Config.SettingsPermission = 'driver'

-- Command that opens the 2-Step panel (driver seat of a fitted vehicle).
Config.MenuCommand = 'antilag'

-- Allow picking any colour with the colour picker, not just the presets.
Config.AllowCustomColour = true

-- Default colour for newly fitted vehicles (a preset key below).
Config.DefaultFlameColour = 'stock'

-- The tint is multiplied onto GTA's flame texture, so bright saturated colours read best.
-- rgb = nil means untouched stock GTA flame. 'rainbow' cycles through the spectrum shot by shot.
-- How coloured flames are drawn. GTA's normal backfire flame is orange and ignores tint, so
-- coloured flames use a different GTA FLAME effect that is tinted instead.
-- In a car, type /antilagfx to see every option below in your colour (or /antilagfx 3 for one),
-- then set Config.ColourFx to the number that looks best.
--   hideStock = true  -> only the coloured flame (no orange flame underneath)
--   rot = { pitch, roll, yaw } to aim the flame out of the back of the car
-- Got a custom recoloured flame particle (.ypt) streamed on your server? Add it here as
-- another entry with its asset and effect name.
Config.ColourFx = 1
Config.ColourFxOptions = {
    { label = 'Nitrous exhaust flame',       asset = 'veh_xs_vehicle_mods', name = 'veh_nitrous', scale = 1.2, looped = true, durationMs = 170, hideStock = true },
    { label = 'Nitrous + stock flame',       asset = 'veh_xs_vehicle_mods', name = 'veh_nitrous', scale = 1.0, looped = true, durationMs = 170, hideStock = false },
    { label = 'Jet afterburner flame',       asset = 'core', name = 'veh_exhaust_afterburner', scale = 1.2, looped = true, durationMs = 170, hideStock = true },
    { label = 'Fire jet (A)',                asset = 'core', name = 'ent_sht_flame', scale = 0.6, looped = true, durationMs = 170, rot = { 90.0, 0.0, 0.0 }, hideStock = true },
    { label = 'Fire jet (B)',                asset = 'core', name = 'ent_sht_flame', scale = 0.6, looped = true, durationMs = 170, rot = { -90.0, 0.0, 0.0 }, hideStock = true },
    { label = 'Wreck fire',                  asset = 'core', name = 'fire_wrecked_plane_cockpit', scale = 0.35, looped = true, durationMs = 200, hideStock = true },
    { label = 'Tinted backfire (one-shot)',  asset = 'core', name = 'veh_backfire', scale = 1.0, looped = false, hideStock = true },
    { label = 'Tinted backfire (looped)',    asset = 'core', name = 'veh_backfire', scale = 1.0, looped = true, durationMs = 140, hideStock = true },
}

-- Coloured light flash at the exhaust on every flame (also for stock, in orange).
Config.FlameGlow = true
Config.FlameGlowRange = 3.0       -- metres
Config.FlameGlowIntensity = 8.0

-- 30 colours for the panel swatch grid. Keep the keys stable: they are what is saved per plate.
Config.FlameColours = {
    { key = 'stock',    label = 'Fire',        rgb = nil },
    { key = 'rainbow',  label = 'Rainbow',     rgb = 'rainbow' },
    { key = 'white',    label = 'White hot',   rgb = { 255, 255, 255 } },
    { key = 'blue',     label = 'Blue',        rgb = { 40, 120, 255 } },
    { key = 'cyan',     label = 'Cyan',        rgb = { 0, 230, 255 } },
    { key = 'sky',      label = 'Sky',         rgb = { 120, 200, 255 } },
    { key = 'navy',     label = 'Navy',        rgb = { 30, 60, 200 } },
    { key = 'indigo',   label = 'Indigo',      rgb = { 90, 80, 240 } },
    { key = 'violet',   label = 'Violet',      rgb = { 140, 0, 255 } },
    { key = 'purple',   label = 'Purple',      rgb = { 170, 60, 255 } },
    { key = 'lavender', label = 'Lavender',    rgb = { 190, 140, 255 } },
    { key = 'magenta',  label = 'Magenta',     rgb = { 255, 0, 255 } },
    { key = 'pink',     label = 'Pink',        rgb = { 255, 50, 190 } },
    { key = 'rose',     label = 'Rose',        rgb = { 255, 0, 110 } },
    { key = 'red',      label = 'Red',         rgb = { 255, 25, 25 } },
    { key = 'crimson',  label = 'Crimson',     rgb = { 220, 20, 60 } },
    { key = 'orange',   label = 'Orange',      rgb = { 255, 120, 0 } },
    { key = 'amber',    label = 'Amber',       rgb = { 255, 180, 0 } },
    { key = 'gold',     label = 'Gold',        rgb = { 230, 190, 50 } },
    { key = 'yellow',   label = 'Yellow',      rgb = { 255, 235, 40 } },
    { key = 'lime',     label = 'Lime',        rgb = { 170, 255, 0 } },
    { key = 'green',    label = 'Green',       rgb = { 40, 255, 60 } },
    { key = 'mint',     label = 'Mint',        rgb = { 140, 255, 170 } },
    { key = 'emerald',  label = 'Emerald',     rgb = { 0, 200, 110 } },
    { key = 'teal',     label = 'Teal',        rgb = { 0, 190, 170 } },
    { key = 'aqua',     label = 'Aqua',        rgb = { 60, 255, 220 } },
    { key = 'peach',    label = 'Peach',       rgb = { 255, 200, 160 } },
    { key = 'bronze',   label = 'Bronze',      rgb = { 205, 127, 50 } },
    { key = 'silver',   label = 'Silver',      rgb = { 190, 200, 215 } },
    { key = 'plum',     label = 'Plum',        rgb = { 170, 70, 130 } },
}

---------------------------------------------------------------------
-- V5.0 2-STEP PANEL
---------------------------------------------------------------------
Config.UI = {
    Title = 'SP ANTILAG - 2STEP',
    Accent = '#2F8CFF',      -- main blue
    AccentGlow = '#5FB0FF',  -- lighter blue for glows / hovers
}

-- Compatibility mode (per vehicle): some exhausts will not show the normal colour effect.
-- Ticking "Compatible" in the panel uses this Config.ColourFxOptions entry instead.
Config.CompatColourFx = 8

-- Exhaust sound types, picked in the panel (synth sound mode only). Selecting one plays a preview.
--   pitch = frequency multiplier, length = decay multiplier, crack = sharpness of the front edge
Config.SoundTypes = {
    { key = 'classic', label = 'Antilag 1 - Classic', pitch = 1.00, length = 1.00, crack = 1.00 },
    { key = 'deep',    label = 'Antilag 2 - Deep',    pitch = 0.72, length = 1.30, crack = 0.80 },
    { key = 'sharp',   label = 'Antilag 3 - Sharp',   pitch = 1.35, length = 0.75, crack = 1.40 },
    { key = 'rally',   label = 'Antilag 4 - Rally',   pitch = 1.10, length = 0.90, crack = 1.25 },
    { key = 'drift',   label = 'Antilag 5 - Drift',   pitch = 0.90, length = 1.15, crack = 1.10 },
    { key = 'thunder', label = 'Antilag 6 - Thunder', pitch = 0.60, length = 1.55, crack = 0.90 },
    { key = 'race',    label = 'Antilag 7 - Race',    pitch = 1.20, length = 0.65, crack = 1.60 },
    { key = 'muscle',  label = 'Antilag 8 - Muscle',  pitch = 0.80, length = 1.20, crack = 1.00 },
}

-- Intensity levels. While you hold the limiter the 2-step fires a continuous barrage
-- (like a real 2-step): one shot every gap ms (random between min and max), each shot
-- picked from mix by weight. flame multiplies the flame size, chance = chance each
-- shot actually fires (lower = more ragged), maxSpeed = 2-step speed window (km/h).
Config.Intensity = {
    soft = {
        label = 'Soft', flame = 0.80, chance = 0.80, maxSpeed = 8.0,
        gap = { 190, 270 },
        mix = { pop = 0.70, bang = 0.30 },
    },
    moderate = {
        label = 'Moderate', flame = 1.00, chance = 0.95, maxSpeed = 12.0,
        gap = { 130, 180 },
        mix = { pop = 0.45, bang = 0.47, mega = 0.08 },
    },
    max = {
        label = 'Maximum', flame = 1.25, chance = 1.0, maxSpeed = 16.0,
        gap = { 105, 150 },
        mix = { pop = 0.30, bang = 0.50, mega = 0.15, big = 0.05 },
    },
}

-- Launch control: hold the handbrake + throttle while stopped. RPM is held at the limiter
-- set in the panel and the 2-step fires at the launch intensity. Release the handbrake to go.
Config.LaunchControl = {
    HoldControl = 76,        -- 76 = handbrake (SPACE / RB)
    MinRpm = 0.45,           -- lowest limiter the panel allows (0.0 - 1.0 of redline)
    MaxRpm = 0.95,
    DefaultRpm = 0.70,
}

-- Popcorn mode: while on the limiter, a chance of a rapid-fire string of pops.
Config.Popcorn = {
    Chance = 0.35,
    CooldownMs = 2200,
    Shots = { 6, 10 },       -- min, max pops in a string
    GapMs = { 75, 110 },     -- min, max gap between them
}

-- Flame size slider range in the panel (multiplier on every flame).
Config.FlameSize = { Min = 0.5, Max = 2.0, Default = 1.0 }

-- Hotbar: three presets per vehicle. Press the key while driving to open it, then 1 / 2 / 3.
Config.Hotbar = {
    Enabled = true,
    Key = 'N',               -- default keybind (players can rebind in GTA settings > FiveM)
}

-- Test mode (Colors tab > TEST): the car is frozen, hold handbrake + throttle to rev and see
-- the unsaved flame, firing at the draft's intensity. Backspace ends it.
