Config = {}
Config.KitItem = 'antilag_kit'
Config.InstallTime = 10000
Config.RemoveTime = 10000
Config.MechanicJobs = { mechanic=true, mechanic2=true }

Config.MinSpeedKmh = 5.0
Config.Range = 220.0

-- V4.4.2 sound source:
--   'synth'  = pops/bangs generated by the resource itself (html/index.html). Always works,
--              no GTA audio banks needed. Volume/muffling by distance. (default)
--   'native' = GTA soundsets below. Depends on game audio banks; can be silent on some setups.
Config.SoundMode = 'synth'
Config.SoundVolume = 0.9   -- 0.0 - 1.5
Config.SoundRange = 120.0  -- metres; beyond this nearby players hear nothing

-- Native GTA audio (only used when Config.SoundMode = 'native'). Optional `bank = '...'`
-- per sound is loaded with RequestScriptAudioBank first. These are emitted FROM the vehicle, so GTA handles 3D positioning.
Config.NativeSounds = {
    pop  = { name = 'BOOT_POP', set = 'DLC_VW_BODY_DISPOSAL_SOUNDS' },
    bang = { name = 'Explosion_01', set = 'FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS' },
    mega = { name = 'Explosion_04', set = 'FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS' }
}

-- V4 uses driver input instead of addon-dependent RPM values.
Config.LimiterThrottle = 0.82
Config.LimiterHoldMs = 300
Config.LimiterCooldownMs = 720
Config.LiftThrottleBefore = 0.55
Config.LiftThrottleAfter = 0.08
Config.LiftCooldownMs = 520

-- Burst patterns: { kind, gap after this shot in ms }. kind = 'pop' | 'bang' | 'mega'.
-- Keep gaps >= 75ms so nearby players receive every shot (server rate gate is 70ms).
Config.LimiterSequence = {      -- held throttle, stationary
    { 'pop', 85 }, { 'bang', 110 }, { 'pop', 85 }, { 'mega', 0 }
}
Config.LiftSequence = {         -- lift off at speed
    { 'bang', 100 }, { 'pop', 90 }, { 'mega', 0 }
}

Config.FlameScale = 1.55
Config.BigFlameScale = 2.15

---------------------------------------------------------------------
-- V4.4 POPS & BANGS (overrun crackle)
---------------------------------------------------------------------
-- A "pops & bangs" map: while coasting off-throttle the exhaust keeps crackling
-- with irregular pops and the occasional bang until you get back on it or slow down.
-- Can be switched on/off per vehicle from the /antilag menu.
Config.PopsBangs = {
    Enabled = true,          -- master switch for the whole feature
    DefaultOn = true,        -- state for newly fitted vehicles
    MinSpeedKmh = 25.0,      -- only crackle above this speed
    MaxThrottle = 0.08,      -- counts as "off throttle" at or below this
    StartDelayMs = 350,      -- wait after lift-off before the crackle starts (lets the lift burst play)
    MaxDurationMs = 4500,    -- stop crackling after this long on the overrun
    MinGapMs = 90,           -- shortest gap between pops (server rate gate is 70ms)
    MaxGapMs = 260,          -- longest gap between pops
    BangChance = 0.30,       -- chance any shot is a bang instead of a pop
    MegaChance = 0.15,       -- chance any shot is a mega bang
    FlameChance = 0.55,      -- chance a plain pop also spits a flame (bangs always flame)
}

---------------------------------------------------------------------
-- V4.4 FLAME COLOURS
---------------------------------------------------------------------
-- Who may change a fitted vehicle's flame colour / pops & bangs setting:
--   'driver'   = whoever is in the driver seat of a fitted vehicle
--   'mechanic' = only mechanics (Config.MechanicJobs) in the driver seat
Config.SettingsPermission = 'driver'

-- Command that opens the settings menu (driver seat of a fitted vehicle).
Config.MenuCommand = 'antilag'

-- Allow picking any colour with the colour picker, not just the presets.
Config.AllowCustomColour = true

-- Default colour for newly fitted vehicles (a preset key below).
Config.DefaultFlameColour = 'stock'

-- The tint is multiplied onto GTA's flame texture, so bright saturated colours read best.
-- rgb = nil means untouched stock GTA flame. 'rainbow' cycles through the spectrum shot by shot.
-- How coloured flames are drawn. GTA's backfire flame is orange and a tint multiplies it,
-- so it cannot turn blue/green/etc by itself. A second, tintable effect is added instead.
-- In a car, type /antilagfx to see every option below in your colour (or /antilagfx 3 for one),
-- then set Config.ColourFx to the number that looks best.
--   hideStock = true  -> only the coloured effect (no orange flame underneath)
Config.ColourFx = 1
Config.ColourFxOptions = {
    { label = 'Firework shot burst',       asset = 'scr_indep_fireworks', name = 'scr_indep_firework_shotburst', scale = 0.35, hideStock = true },
    { label = 'Firework shot + flame',     asset = 'scr_indep_fireworks', name = 'scr_indep_firework_shotburst', scale = 0.30, hideStock = false },
    { label = 'Firework trail burst',      asset = 'scr_indep_fireworks', name = 'scr_indep_firework_trailburst', scale = 0.20, hideStock = true },
    { label = 'Firework fountain (A)',     asset = 'scr_indep_fireworks', name = 'scr_indep_firework_fountain', scale = 0.45, looped = true, durationMs = 180, rot = { 90.0, 0.0, 0.0 }, hideStock = true },
    { label = 'Firework fountain (B)',     asset = 'scr_indep_fireworks', name = 'scr_indep_firework_fountain', scale = 0.45, looped = true, durationMs = 180, rot = { -90.0, 0.0, 0.0 }, hideStock = true },
    { label = 'Nitrous exhaust flame',     asset = 'veh_xs_vehicle_mods', name = 'veh_nitrous', scale = 1.0, looped = true, durationMs = 160, hideStock = true },
    { label = 'Tinted backfire (old way)', asset = 'core', name = 'veh_backfire', scale = 1.0, looped = true, durationMs = 140, hideStock = true },
}

-- Coloured light flash at the exhaust on every flame (also for stock, in orange).
Config.FlameGlow = true
Config.FlameGlowRange = 3.0       -- metres
Config.FlameGlowIntensity = 8.0

Config.FlameColours = {
    { key = 'stock',   label = 'Stock (orange)', rgb = nil },
    { key = 'blue',    label = 'Blue',           rgb = { 40, 120, 255 } },
    { key = 'cyan',    label = 'Cyan',           rgb = { 0, 230, 255 } },
    { key = 'green',   label = 'Green',          rgb = { 40, 255, 60 } },
    { key = 'purple',  label = 'Purple',         rgb = { 170, 60, 255 } },
    { key = 'pink',    label = 'Pink',           rgb = { 255, 50, 190 } },
    { key = 'red',     label = 'Red',            rgb = { 255, 25, 25 } },
    { key = 'white',   label = 'White hot',      rgb = { 255, 255, 255 } },
    { key = 'rainbow', label = 'Rainbow',        rgb = 'rainbow' },
}
